# Generated by Django 6.0.7 on 2026-07-28 05:36

import parties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.CharField(default=parties.models.generate_party_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tally_export_name', models.CharField(blank=True, max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('party_type', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('cellphone', models.CharField(blank=True, max_length=20)),
                ('land_line', models.CharField(blank=True, max_length=20)),
                ('appear_under', models.CharField(blank=True, max_length=100)),
                ('inward_tax', models.CharField(blank=True, max_length=100)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('enable_portal', models.BooleanField(default=False)),
                ('pan', models.CharField(blank=True, max_length=20)),
                ('gst_supply_type', models.CharField(blank=True, max_length=100)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('create_ledger', models.BooleanField(default=True)),
                ('opening_balance', models.FloatField(default=0)),
                ('balance_type', models.CharField(blank=True, max_length=100)),
                ('due_in_days_type', models.CharField(blank=True, max_length=100)),
                ('region_name', models.CharField(blank=True, max_length=255)),
                ('area_name', models.CharField(blank=True, max_length=255)),
                ('route', models.CharField(blank=True, max_length=255)),
                ('from_date', models.CharField(blank=True, max_length=50)),
                ('to_date', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('transactions', models.CharField(blank=True, max_length=100)),
                ('serviced_by', models.CharField(blank=True, max_length=255)),
                ('smart_tags', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
